[2024-07-03T14:32:49.670+0000] {processor.py:161} INFO - Started process (PID=598) to work on /opt/airflow/dags/reading_dag.py
[2024-07-03T14:32:49.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-03T14:32:49.676+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:32:49.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:32:49.755+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:32:49.742+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 8, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable hello does not exist'
[2024-07-03T14:32:49.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:32:49.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.157 seconds
[2024-07-03T14:33:19.971+0000] {processor.py:161} INFO - Started process (PID=656) to work on /opt/airflow/dags/reading_dag.py
[2024-07-03T14:33:19.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-03T14:33:19.975+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:33:19.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:33:20.058+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:33:20.051+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 8, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable hello does not exist'
[2024-07-03T14:33:20.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:33:20.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.153 seconds
[2024-07-03T14:34:10.766+0000] {processor.py:161} INFO - Started process (PID=710) to work on /opt/airflow/dags/reading_dag.py
[2024-07-03T14:34:10.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-03T14:34:10.769+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:34:10.768+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:34:10.801+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:34:10.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 8, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable hello does not exist'
[2024-07-03T14:34:10.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:34:10.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.059 seconds
[2024-07-03T14:34:40.869+0000] {processor.py:161} INFO - Started process (PID=764) to work on /opt/airflow/dags/reading_dag.py
[2024-07-03T14:34:40.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-03T14:34:40.875+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:34:40.874+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:34:40.900+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:34:40.895+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 8, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable hello does not exist'
[2024-07-03T14:34:40.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:34:40.913+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.051 seconds
[2024-07-03T14:35:11.470+0000] {processor.py:161} INFO - Started process (PID=821) to work on /opt/airflow/dags/reading_dag.py
[2024-07-03T14:35:11.471+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-03T14:35:11.472+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:35:11.472+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:35:11.511+0000] {logging_mixin.py:188} INFO - [2024-07-03T14:35:11.502+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 8, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable hello does not exist'
[2024-07-03T14:35:11.514+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-03T14:35:11.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.062 seconds
